### ISSUE TITLE
Star this repository

### ISSUE THREAD

**Issue by shreyanshdwivedi** [GeekHaven/Aparoksha-18#10]
Open to everyone. Upload a screenshot to be eligible for points

**Comment by Jigar3** [comment]
![screenshot_2018-01-11-11-31-53-147_com android chrome](https://user-images.githubusercontent.com/32068121/34810719-1d7e8fea-f6c3-11e7-8dfd-935b908ae413.png)

**Comment by swaager** [comment]
![gn0me](https://user-images.githubusercontent.com/29673845/34811164-8d5d894a-f6c5-11e7-9743-144b6c281fab.png)

**Comment by hacker1x1x1** [comment]
![screenshot_20180111-121252](https://user-images.githubusercontent.com/34509429/34811840-f2586236-f6c8-11e7-994d-42feab651fe5.jpg)

**Comment by rahulkumaran** [comment]
![screenshot from 2018-01-11 12-23-39](https://user-images.githubusercontent.com/26206171/34812125-50c1693e-f6ca-11e7-96a3-8eb169bce10f.png)

**Comment by GOVINDDIXIT** [comment]
![capture](https://user-images.githubusercontent.com/32304546/34813845-7e546192-f6d1-11e7-82ed-3919e67caa33.PNG)

**Comment by AK-007** [comment]
![screenshot 49](https://user-images.githubusercontent.com/26346816/34814018-3acef83c-f6d2-11e7-999a-c7e21ad55705.png)

**Comment by namantw** [comment]
![screenshot_2018-01-11-13-19-16-189_com android chrome](https://user-images.githubusercontent.com/31323328/34814003-2be99a5c-f6d2-11e7-9294-a4f6e7050361.png)

**Comment by aadixiiita** [comment]
![screenshot_20180111-132547](https://user-images.githubusercontent.com/34688457/34814282-1092f0f4-f6d3-11e7-994d-c5f1889ae926.png)

**Comment by Re42** [comment]
![image](https://user-images.githubusercontent.com/33805964/34814437-a0f802e2-f6d3-11e7-8657-a1c23e2684cd.png)

**Comment by adiagg2000** [comment]
![screenshot_20180111-132948](https://user-images.githubusercontent.com/33027339/34814453-b223202e-f6d3-11e7-96d5-4d26befd94c3.png)

**Comment by prathamprakash29** [comment]
![image](https://user-images.githubusercontent.com/30841366/34814955-8cdcf8ba-f6d5-11e7-82bb-460260068d0c.png)

**Comment by Tachyon01** [comment]
![screenshot_20180111-141311](https://user-images.githubusercontent.com/34283302/34816193-301ceefa-f6da-11e7-9fa0-0f15f1c64ffe.png)

**Comment by permanent-bnsl** [comment]
![screenshot](https://user-images.githubusercontent.com/35285444/34816420-e484108a-f6da-11e7-974b-e586c26e2d7a.png)

**Comment by RudRA-8** [comment]
![image](https://user-images.githubusercontent.com/33032175/34816494-1ba757c0-f6db-11e7-83fb-115ddc17dd94.png)

**Comment by dojutsu-user** [comment]
![capture](https://user-images.githubusercontent.com/29149191/34820391-69422d1a-f6e6-11e7-8ade-2e489ee8b0ee.PNG)

**Comment by helios1101** [comment]
![capture8](https://user-images.githubusercontent.com/26597930/34824887-57cbf5c4-f6f6-11e7-9160-2f4737f5eaab.JPG)

**Comment by surasnayak** [comment]
Done!
![screenshot from 2018-01-12 01-02-43](https://user-images.githubusercontent.com/21239888/34829320-531a2676-f706-11e7-808d-03e98f7f29a5.png)

**Comment by Panda2498** [comment]
![aparoksha](https://user-images.githubusercontent.com/34282889/34834183-57ff1d98-f717-11e7-83c5-2dc24c916efe.PNG)

**Comment by ananya-agrawal** [comment]
![c](https://user-images.githubusercontent.com/33188930/34836118-e3d6a5b6-f71c-11e7-9d26-1e43ff843cfb.png)

**Comment by brain-sick** [comment]
![5](https://user-images.githubusercontent.com/34164978/34844419-6878c082-f737-11e7-8075-5d77545fce33.png)

**Comment by strikertanmay** [comment]
![screenshot from 2018-01-12 02-27-07](https://user-images.githubusercontent.com/32292953/34847059-25c27e64-f740-11e7-8b62-f8fd40dc1a02.png)

**Comment by illseption** [comment]
![starred_rep_screenshot](https://user-images.githubusercontent.com/28671093/34871221-d61f17d2-f7b2-11e7-9b9f-2441fea9c00b.png)

**Comment by maverick0004** [comment]
![screenshot from 2018-01-12 16-58-08](https://user-images.githubusercontent.com/33194760/34873106-d269e7dc-f7b9-11e7-985d-30cf1bdfd78a.png)

**Comment by Anubhav2000** [comment]
![capture](https://user-images.githubusercontent.com/33462670/34887689-5c9fa1fc-f7ed-11e7-923e-b364e872771f.PNG)

**Comment by RohanShekhawat** [comment]
![capture](https://user-images.githubusercontent.com/34987773/34889599-9709bb28-f7f4-11e7-8547-560149badf42.PNG)

**Comment by Esha23** [comment]
![screenshot-2018-1-12 geekhaven aparoksha-18](https://user-images.githubusercontent.com/35305010/34895379-80ab4150-f80b-11e7-907e-c5fca43b4e7b.png)

**Comment by DEVILCODER-SB99** [comment]
![screenshot 14](https://user-images.githubusercontent.com/33373098/34918468-d2b48ed4-f978-11e7-888d-56f98a357251.png)

**Comment by pradeepgangwar** [comment]
We got some concerns regarding starring a repo. We are sorry but we have to close this issue.

**Comment by falconis** [comment]
![staridk](https://user-images.githubusercontent.com/30634978/36046547-4cc817c8-0dff-11e8-9d7e-00e1f57b173b.png)
