### ISSUE TITLE
Add timestamp when a user registers

### ISSUE THREAD

**Issue by pradeepgangwar** [GeekHaven/Aparoksha-18#11]
On registration page when a user registers, currently we do not store timestamp of registration. Using proper code add a method to store timestamp also. Name of column in DB can anything for now we will update DB accordingly.

**Comment by aadixiiita** [comment]
Can i try this ???

**Comment by pradeepgangwar** [comment]
Yeah sure, go for it. @aadixiiita

**Comment by pradeepgangwar** [comment]
@aadixiiita Still working?

**Comment by aadixiiita** [comment]
Yes sir i m trying ...
