### ISSUE TITLE
Suggest a template for beta version of Aparoksha website

### ISSUE THREAD

**Issue by shreyanshdwivedi** [GeekHaven/Aparoksha-18#14]
Opened to everyone. But only the template selected will be awarded with the points

**Comment by Ace-Bansal** [comment]
[https://www.downloadfreethemes.download/flathost-wordpress-hosting-theme-whmcs/](https://www.downloadfreethemes.download/flathost-wordpress-hosting-theme-whmcs/)

Please checkout this template. Do take a look at the multipage preview :)

**Comment by pradeepgangwar** [comment]
@shreyanshdwivedi Let's close this issue. We already have our landing page live.

**Comment by shreyanshdwivedi** [comment]
Ya sure!!
