### ISSUE TITLE
Design About page 

### ISSUE THREAD

**Issue by pradeepgangwar** [GeekHaven/Aparoksha-18#19]
Design about us page keeping layout simple and same as sponsors page with a footer including all social links.

**Comment by falconis** [comment]
I'd like to take this

**Comment by pradeepgangwar** [comment]
Assigned to you.

**Comment by pradeepgangwar** [comment]
@falconis status?

**Comment by falconis** [comment]
I didn't get the time to work on it. I'll complete it by Tuesday.

**Comment by falconis** [comment]
Exactly, what should be in the about page? Should I write the information on my own or is there a source for it?

**Comment by pradeepgangwar** [comment]
ok first of all put some random data of about 100 words in it ... and then social links below it . I will provide rest of the data.

**Comment by falconis** [comment]
Alright! I'll get this done tomorrow.
