### ISSUE TITLE
Bug:fix background colour of boxes on register page [Mobile]

### ISSUE THREAD

**Issue by shreyanshdwivedi** [GeekHaven/Aparoksha-18#2]
When you open the box on register page in mobile view, background colour of box remains black till you click on it.

**Comment by permanentb** [comment]
@shreyanshdwivedi sir please assign me .

**Comment by shreyanshdwivedi** [comment]
Assigned to @permanentb

**Comment by Panda2498** [comment]
Can I work on this issue?

**Comment by shreyanshdwivedi** [comment]
@Panda2498, this issue is already assigned to @permanent-bnsl. You can try another issue to work upon

**Comment by pradeepgangwar** [comment]
@permanent-bnsl Still working?

**Comment by pradeepgangwar** [comment]
@permanent-bnsl unassigned.

**Comment by Ace-Bansal** [comment]
May I work on this?

**Comment by Ace-Bansal** [comment]
@pradeepgangwar The background color of the box isn't changing in the mobile view. I tried adding in a media queries but it's still not working.

**Comment by pradeepgangwar** [comment]
@Ace-Bansal I am not sure about what's making that issue. But if u are not able to figure out. You can leave it and work on other issue.  I will let u know if there is something for u to learn once i figure out what's behind this issue. All the best.

**Comment by Ace-Bansal** [comment]
@pradeepgangwar That would be great. Thank you! :-)
