### ISSUE TITLE
Run this project on your local computer

### ISSUE THREAD

**Issue by shreyanshdwivedi** [GeekHaven/Aparoksha-18#3]
This task is open to all. Anyone who run this project on his/her local computer has to comment a gif in this thread to be eligible for points.
Refer README for help.

**Comment by AK-007** [comment]
![aparoksha](https://user-images.githubusercontent.com/26346816/34775947-fcfaf5c0-f63a-11e7-84fb-f5a2fc74568b.gif)

**Comment by namantw** [comment]
![gif-180110_235159 1](https://user-images.githubusercontent.com/31323328/34788668-4df2b744-f661-11e7-99d5-91f5fe4ba9d2.gif)

**Comment by adiagg2000** [comment]
![main](https://user-images.githubusercontent.com/33027339/34791180-2cd3ab3c-f66a-11e7-9368-f8b94d0d59eb.gif)

**Comment by adiagg2000** [comment]
![main](https://user-images.githubusercontent.com/33027339/34791282-88f25f6c-f66a-11e7-8936-cd3c9ed1738a.gif)

**Comment by helios1101** [comment]
![capture 3](https://user-images.githubusercontent.com/26597930/34793914-00a15614-f673-11e7-96fb-fa9909e6fbf5.gif)

**Comment by hacker1x1x1** [comment]
![aparoksha](https://user-images.githubusercontent.com/34509429/34809139-f5b952ae-f647-11e7-9db8-8724a8f3c71f.gif)

**Comment by Jigar3** [comment]
Setup on ubunu using LAMP stack
![giphy-downsized-large](https://user-images.githubusercontent.com/32068121/34809602-078638e8-f6bc-11e7-9a2e-0d3d4c540946.gif)

**Comment by Re42** [comment]
![running](https://user-images.githubusercontent.com/33805964/34815473-74096808-f6d7-11e7-81ed-da2f335d1b59.gif)

**Comment by aadixiiita** [comment]
![screenshot from 2018-01-11 19-05-08](https://user-images.githubusercontent.com/34688457/34828108-738549c6-f702-11e7-9872-d5dd1f6cff4d.png)

**Comment by ShiningSaurabh** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/34839782/34848859-6ed2600a-f746-11e7-94f9-723aeee426fe.gif)

**Comment by surasnayak** [comment]
![surasnayak_localhost](https://user-images.githubusercontent.com/21239888/34868881-33957c60-f7ab-11e7-961e-a6ff4c837cc2.png)

**Comment by swaager** [comment]
![ee1 ogv](https://user-images.githubusercontent.com/29673845/34917255-fdbc32ce-f911-11e7-90f1-e80d4ffdccf3.gif)

**Comment by DEVILCODER-SB99** [comment]
![giphy](https://user-images.githubusercontent.com/33373098/34918419-4e805e72-f978-11e7-8ac5-0bfbdd94cce8.gif)

**Comment by ashraysinha6069** [comment]
![sasa](https://user-images.githubusercontent.com/34709632/35185322-d069e656-fe28-11e7-819d-8f5d0e0aca41.gif)

**Comment by Ace-Bansal** [comment]
![videotogif_2018 01 16_13 58 58](https://user-images.githubusercontent.com/34866483/35299864-b20e8b2c-00ac-11e8-8366-b3a00e86935b.gif)

**Comment by Tlazypanda** [comment]
![giphy-downsized-large](https://user-images.githubusercontent.com/33183263/36052935-c0078d34-0e15-11e8-9ddd-a7e711ddc09d.gif)
