### ISSUE TITLE
Bug: Fix closing animation speed of transition of fest reg and events boxes 

### ISSUE THREAD

**Issue by CodHeK** [GeekHaven/Aparoksha-18#5]
Currently clicking on close button, animation speed of showing of both boxes differ. When closing left box right box appears faster whereas when closing right box left box appears slower. We wan to fix it so that both have same speed.

![apk](https://user-images.githubusercontent.com/21259802/34779490-5d3cb56c-f646-11e7-8df4-5a2b3da717c6.gif)

**Comment by AK-007** [comment]
I would like to work on this.

**Comment by pradeepgangwar** [comment]
assigned to you @AK-007 .
