### ISSUE TITLE
Align closing button in fest registration modal

### ISSUE THREAD

**Issue by CodHeK** [GeekHaven/Aparoksha-18#6]
![screenshot from 2018-01-10 20-40-23](https://user-images.githubusercontent.com/22097366/34779743-1d925db2-f647-11e7-8b49-da1510392c4e.png)

The Cross button looks a bit off

**Comment by Re42** [comment]
Can I take this issue?

**Comment by CodHeK** [comment]
@Re42  Yeah Sure!

**Comment by pradeepgangwar** [comment]
assigned to @Re42

**Comment by Re42** [comment]
Please help me with the question I asked in the pull request comment
