### ISSUE TITLE
Add a Loader 

### ISSUE THREAD

**Issue by CodHeK** [GeekHaven/Aparoksha-18#7]
Provide us with a GIF of the loader you've added

**Comment by ananya-agrawal** [comment]
i will like to do this

**Comment by pradeepgangwar** [comment]
assigned to @ananya-agrawal

**Comment by falconis** [comment]
I'd like to do this if no one is working on it..

**Comment by pradeepgangwar** [comment]
It has a open PR ... let's see if that can be fixed soon.

**Comment by falconis** [comment]
Ohh sorry, didn't check PRs!

**Comment by pradeepgangwar** [comment]
@ananya-agrawal still working ?

**Comment by hacker1x1x1** [comment]
If no one is working on this...
Can I work on this issue?

**Comment by ananya-agrawal** [comment]
@pradeepgangwar yes sir i have seen it .U may close merge it now.
